### ISSUE TITLE
How to apply inbreeding coeffs (F) in Angsd?

### ISSUE THREAD

**Issue by dkainer** [mfumagalli/ngsTools#11]
Hi, if i use ngsF to calculate F for individuals in my population, where do I use it as a prior in Angsd? There seems to be no documentation on this.

cheers
DK

**Comment by fgvieira** [comment]
Hi DK,

inbreeding values are provided to angsd through option `-indF`, that can be either a value (same F for all individuals) or a file with F per individual (one per line, just as ngsF output).
However, keep in mind, that only some analyses in angsd make use of inbreeding (e.g. posterior probs or SFS).

best,
FGV

**Comment by SichongP** [comment]
If I calculated inbreeding coefficients for three separate populations, and want to combine them in angsd to calculate posteriors and to eventually plot a PCA for the three populations, at which step should I combine them? It's not clear to me from the documentation how to feed three inbreeding coef files to ngsd.

**Comment by mfumagalli** [comment]
there is no such feature at the moment; I'd consider calculate the inbreeding coefficient for all samples jointly.
