### ISSUE TITLE
Floating point exception problem in ngsStat

### ISSUE THREAD

**Issue by mlucenaperez** [mfumagalli/ngsTools#12]
Hello,

I am running nsgStat in different populations. No matter which population I used, when I try to get the stats by doing:

`/opt/ngsTools/ngsPopGen/ngsStat -npop 1 -postfiles BIA.unfolded.ref.postprob.saf -outfile BIA.stats.txt -nind 8`

I got the message:  "floating point exception". Output file is generated but empty. The .saf file "seems" normal when I print it. I don't really know what could be causing the problem, so sorry for not giving any hint. Any idea?

I would truly appreciate any input,
Best,
María.

**Comment by kpboh** [comment]
I'm experiencing a similar problem... Following [the tutorial here](https://github.com/mfumagalli/ngsTools/blob/master/TUTORIAL.md). 

Submitted:

 `~/ngsTools/ngsPopGen/ngsStat -npop 2 -postfiles /model_data/AL.saf /model_data/BI_.saf -nind 15 15 -outfile /model_data/AL.BI_ngsstat.stats.txt`

Returned 'floating point exception'. 

Tried again w/ nsites option (per tutorial):

 `~/ngsTools/ngsPopGen/ngsStat -npop 2 -nsites $N_SITES -postfiles /model_data/AL.saf /model_data/BI.saf -nind 15 15 -outfile /model_data/AL.BI_ngsstat.stats.txt`

And returned "Possible error reading SFS, binary file might be broken..."

I thought the problem might be with the change in SAF file format produced by ANGSD, so I regenerated the SAF files following the author's instructions: 

`./realSFS print AL.saf.idx BI.saf.idx -oldout 1`

Then retried the ngsStat command but received the floating point error again.

Thanks in advance for any suggestions!
Regards,
Kevin

**Comment by mfumagalli** [comment]
Dear both,

which version of ANGSD are you using? You should use the latest ones (>0.900) with the latest ngsTools one too. That error is likely to be generated because of incompatibility between versions.
Then, the updated command lines can be found following the latest TUTORIAL on ngsTools.

Please let me know.

Best

Matteo

**Comment by kpboh** [comment]
Matt,
Thanks for the reply. I'm using ANGSD ver 0.911 and ngsTools ver 1.0.1. 
-Kevin

**Comment by mfumagalli** [comment]
OK, one issue is that you always have to specify the number of sites -nsites.
Second, when you get ""Possible error reading SFS, binary file might be broken..."" it is very likely that your values for sample sizes and/or sites are not correct, not compatible with your .saf files.
Hope this helps.

**Comment by kpboh** [comment]
Hi Matteo,
Thanks for the suggestions. One thing that just occurred to me--I estimated the SFS using the -fold option as I don't have access to a great ancestral reference at the moment. Could this be contributing to this issue?

**Comment by mlucenaperez** [comment]
Dear Matteo

Sorry for my late response, I have been trying different options lately. So, first of all -nsites seems to solve the situation. Sorry for that, it was pretty obvious, but I didn't know that it was a mandatory command when you wanted to run it over all the sites; so, again, sorry for that. 

Anyway, I have a couple of questions regarding some unexpected results of the NGSStats (please if you consider that I should move it to a new issue, just ask me to do it). 

This is what I have done:

```
/opt/angsd/misc/realSFS print Pop1.unfolded.ref.postprob.saf.idx > Pop1_sites

wc -l Pop1_sites
1305610656 

/opt/ngsTools/ngsPopGen/ngsStat -npop 1 -postfiles Pop1.unfolded.ref.postprob.saf -nind 12 -nsites 1305610656 -outfile Pop1.stats.txt 
```

So far, so good. However, when I calculate the average of the heterozygosity per site, it was unexpectedly high (0.2!!!). I made a frequency table and check that only 8,4e7 positions seems to have a heterozygosity of nearly 0 , which is approximately 6,5% of the total sites. 

Then, I focus on particular sites with particular heterozygosity values. For instances, 0.218750 which seems to be as abundant as 0. 

```
awk '$4 == "0.218750"' Pop1.stats.txt | head -n1
171800001	171800001	1.000000	0.218750

```
If I print this line in my saf file:
```
awk 'NR==171800001' Pop1_sites
s05214	3178508	-0.000001	-13.682889	-16.615824	-20.378876	-24.352932	-28.544945	-32.799538	-37.296932	-41.868717	-46.790615	-52.114395	-57.618362	-64.404915	-82.649429	-102.180318	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf
```
That was not what I expected. If I understood it correctly, this position seems to be homozygous for the ancestral allele (-0.000001). Positions before and after this one have the same pattern.

I thought that maybe I was misunderstanding something so I took the first 20000 positions in my saf file and sort them by the 3rd field.  

```
head -n 20000 Pop1_sites | awk '{print $3}' | grep -v inf | sort | tail -n10
-0.000316
-0.008772
-0.939112
-32.520485
-34.163971
-41.963238
-43.093460
-83.363380
-94.836245
-98.058574
```

Then I grep the lines and do the calculus handmade. For example:
```
head -n 20000 Pop1_sites |  grep -n 43.093460

12251:s00001	30747	-43.093460	-39.043865	-23.694439	-12.929015	-5.662327	-2.08070-0.958698	-1.178478	-1.958992	-3.382097	-5.320559	-7.356870	-10.261868	-13.110122	-16.830233	-20.954023	-25.915405	-31.991777	-41.034828	-51.265667	-62.297661	-74.999764	-88.604675	-103.278930	-inf
```

The highest log is -0.95, which correspond to 6 copies of a total of 24 (12 individuals). 

H = 2pq ; H = 2*(6/24)*(1-(6/24))
H = 0.375

```
awk 'NR==12251' Pop1.stats.txt 
12251	12251	1.000000	0.394383
```

0.375 is pretty close to 0.3943. All the others are even closer, so maybe the file is broken at some point and the lines don't fit in both files anymore.  That's why I check how many sites I have in total in my stats file:

```
wc -l Pop1.stats.txt
1305610656 
```

Exactly what I was expecting. 

I have found some others positions with the same problem. Even more dramatically:
```

awk 'NR==705610656' Pop1.stats.txt 
705610656	705610656	1.000000	0.468750

awk 'NR==705610656' Pop1_sites 
s20872	862941	-0.000004	-12.688973	-14.695033	-17.603107	-20.793150	-24.272032	-27.888864	-31.834208	-35.956757	-40.557934	-45.721695	-51.244373	-58.103386	-67.146942	-77.755127	-92.441155	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf

```
The last thing that came to my mind: Let's count very very very roughly(**), how many sites "are" homozygous for the ancestral allele in the saf, as they have a high value in the first column:

(**) I know that this is completely heterodoxous way. Probably, it doesn't mean much, but I thought that it could be useful to report it here.


```
awk '$3>=-0.1' Pop1_sites | wc -l
1301886996
``` 

That is 99.7%!  
 

Similar pattern is found with the segregating sites, as you could see in the example. 

Analysis of another 2 populations gave similar results. 

I install the new version ngsTools (as I already had the last version of ANGSD) and repeat everything and it gave me the exact same result. 

I would be really grateful if you can give me any hit on what is going on. I am really lost, and I don't know what else should I check. 

Thanks in advance,

María.

**Comment by mlucenaperez** [comment]
Dear kpboh,
 
From the ngsPopGen tutorial:

IMPORTANT NOTE ii):

The use of folded data (spectrum or sample allele frequencies probabilities) is no longer supported. In case you do not have a reliable ancestral information, please use your reference sequence to polarise your data and follow all the steps as documented here. However, do not attempt to make any inference based on the resulting unfolded reference/non-reference based - site frequency spectrum.

Hope this helps!

María

**Comment by mlucenaperez** [comment]
Dear Matteo,

New update:

When I calculate the average of Watterson and Pairwise for the same population using .thetas.gz file, I got: Watterson: 0.000321901 and pairwise: 0.000432926 which makes perfect sense, but it is incompatible with my results using NGSTools. Anything very obvious that I am missing?

I would truly appreciate any help on the issue from you or any user with any idea,
Thanks in advance,

María.

**Comment by mfumagalli** [comment]
Dear both,
sorry for the late reply.

- yes, a fold spectrum is not supported for multi-population analyses

- Maria, when you compute the nr of polymorphic sites in your example, you use
awk '$3>=-0.1' Pop1_sites | wc -l
which I believe should be
awk '$3<=-0.1' Pop1_sites | wc -l

- it could be that at the beginning/end of your files your sequencing data may have systematically lower quality, so better check the raw data there and eventually fix your filtering

- thanks for checking overlaps with ANGSD, can you send me exactly the command lines you use in both cases (ngsTools and ANGSD) so I can double check? Anyway, I would recommend use ANGSD for summary stats as it implements them in a more efficient way

best

Matteo

**Comment by mlucenaperez** [comment]
Dear Matteo,

When I did awk '$3>=-0.1' Pop1_sites | wc -l, I was trying to get an estimate of non polymorphic sites, not polymorphic ones. 

About the quality of my data, I don't think that's the issue (although it could be) cause I evaluated it quite well: fastQC for every fastq, and then adjust my parameters running and evaluating my sfs. After some test I decided on specific filters such as MaxDepth filter. Quality /mapping quality are quite regular.

The only difference between ANGSD and NGSTools scripts in terms of data used, is that I used folded sfs for theta calculation and unfolded sfs for NGSTools, but I don't think that this explains the difference. My exacts commands are:

For theta calculation:

```
# ANGSD analysis: Theta per site.

# SAF (likelihood):

$ANGSD/angsd -P 8 -b Pop1.bamlist -ref ref.fa -anc ref.fa -out Pop1 \
-uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -baq 1 -C 50 \
-minMapQ 30 -minQ 20 -minInd 6 -setMaxDepth 99 -doCounts 1 \
-GL 1 -doSaf 1 -fold 1 


# SFS:

$ANGSD/misc/realSFS Pop1.saf.idx  -P 10  > Pop1.sfs


# SAF (postprob) + theta:

$ANGSD/angsd -P 8 -b Pop1.bamlist -ref ref.fa -anc ref.fa -out Pop1.postprob \
-uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -baq 1 -C 50 \
-minMapQ 30 -minQ 20 -minInd 6 -setMaxDepth 99 -doCounts 1 \
-GL 1 -doSaf 1 -fold 1 \
-doThetas 1 -pest Pop1.sfs 


# Make bed theta:

$NGSTOOLS/thetaStat make_bed Pop1.postprob.thetas


# Transforming theta:

cat KIR.postprob.thetas | awk 'NR>1 {print  "e("$4")"}' | bc -l > Pop1_pairwise
cat KIR.postprob.thetas | awk 'NR>1 {print  "e("$3")"}' | bc -l > Pop1_watterson


# Calculating average

# Pi

awk '{ sum += $1 } END {print "SUM="sum,"NR="NR, "AVERAGE="sum/(NR) }' Pop1_pairwise 
SUM=565233 NR=1305610656 AVERAGE=0.000432926

# Waterson

awk '{ sum += $1 } END {print "SUM="sum,"NR="NR, "AVERAGE="sum/(NR) }' Pop1_watterson 
SUM=420278 NR=1305610656 AVERAGE=0.000321901
````

For NGSTools:

```
# NGSTools: Stats.


# SAF unfolded (likelihood):

 
$ANGSD/angsd -P 8 -b Pop1.bamlist -ref ref.fa -anc ref.fa -out Pop1.unfolded.ref \
-uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -baq 1 -C 50 \
-minMapQ 30 -minQ 20 -minInd 6 -setMaxDepth 99 -doCounts 1 \
-GL 1 -doSaf 1 
 

# SFS:

$ANGSD/misc/realSFS Pop1.unfolded.ref.saf.idx  -P 4  > Pop1.unfolded.ref.sfs


# SAF unfolded (postprob):


$ANGSD/angsd -P 8 -b Pop1.bamlist -ref ref.fa -anc ref.fa -out Pop1.unfolded.ref.postprob \
-uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -baq 1 -C 50 \
-minMapQ 30 -minQ 20 -minInd 6 -setMaxDepth 99 -doCounts 1 \
-GL 1 -doSaf 1 -pest Pop1.unfolded.ref.sfs 
      

zcat Pop1.unfolded.ref.postprob.saf.gz > Pop1.unfolded.ref.postprob.saf 


# To calculate stats of only one population the command would be:

$ANGSD/misc/realSFS print Pop1.unfolded.ref.postprob.saf.idx > Pop1_sites


# Calculating how many sites:

wc -l Pop1_sites 

1305610656 Pop1_sites


# Running stats:

/opt/ngsTools/ngsPopGen/ngsStat -npop 1 -postfiles Pop1.unfolded.ref.postprob.saf -nind 12 -nsites 1305610656 -outfile Pop1.stats.txt 


# Calculating the average:

awk '{print $4}' Pop1.stats.txt | grep -v nan | awk '{ sum += $4 } END {print "SUM="sum,"NR="NR, "AVERAGE="sum/NR }'

Pop1 --> SUM=2.79414e+08 NR=1305579735 AVERAGE=0.214015

```

If you asked me my impression, it seems that while running NGSTools it keeps summing up something to the columns, in a way that at the beginning there's a lots of invariant positions (as it should be) but they are getting less and less frequent while processing the file, and at the very end it's like 0 is 0.15.... in terms of programming language, it's like there's a counter that doesn't get to zero properly after every iteration. I don't know if this make any sense... 

Thanks a lot,

María.

**Comment by mfumagalli** [comment]
Thank you Maria for your feedback.
This could be either the use of an unfolded spectrum generated using the reference as ancestral (we never tested the effect on the estimates) or indeed a bug in ngsStat.
Perhaps towards the end of your file it is more likely that the reference alleles is not the common one.
In case of no ancestral information, I would use the folded spectrum as implemented in ANGSD.
In the meantime I will look at iterators in ngsStat.
Thanks
Best
Matteo

**Comment by mfumagalli** [comment]
Hi Maria, not really urgent but it would be interesting to see whether you get the same weird behaviour in ngsStat if you use a uniform SFS as prior (to rule out effect of wrong unfolded SFS).
Thanks
Matteo

**Comment by mlucenaperez** [comment]
Hi Matteo,

I run it using an uniform SFS that I did manually (I don't know if there's another way) and the result didn't seem to solve the weird behavior. 
```
awk '{print $4}' Pop1.uniform.stats.txt | grep -v nan | awk '{ sum += $1 } END {print "SUM="sum,"NR="NR, "AVERAGE="sum/NR }'
SUM=2.82383e+08 NR=1305579735 AVERAGE=0.216289
```
Anything else that I could help? 

Thanks,
María.

**Comment by mfumagalli** [comment]
Thanks Maria for your help. I will test it on some more data and try to figure out what's happening. In the meantime of course please use ANGSD implementation.
Best
Matteo
