### ISSUE TITLE
ngsCovar error

### ISSUE THREAD

**Issue by biozzq** [mfumagalli/ngsTools#15]
Hi @mfumagalli, @fgvieira 

I have run `doGeno 32` for each chromosome with specified high quality sites (filtered by depth, SNP_pvalue, hwe_pvalue, SB3, and so on) 
`angsd -bam bam.list -only_proper_pairs 1 -uniqueOnly 1 -remove_bads 1 -minQ 20 -minMapQ 30 -C 50 -ref ref.fa -r $i -out $i -doMaf 1 -doMajorMinor 1 -doGeno 32 -doPost 1 -GL 1 -doCounts 1 -P 5 -doGlf 2 -sites $i.site`
but when I do `ngsCovar -probfile test.geno -outfile test.covar -nind $minindividual -nsites $sites -call 0 -norm 0` for one chromosome according to the tutorial, it just give me an error like following,
`-> Possible error read GENO, binary file might be broken...`
I do not know why because everything proceeded very smoothly except `ngsCovar`. I need your help.

Many thanks.
Best

**Comment by mfumagalli** [comment]
Hi there,

this error usually comes out when the numbers of samples and sites you set do not match with the .geno file itself.
A quick trick is to look at the dimension of the unzipped .geno file; divide it by 8 and then by 3 and then by the number of sites: if all is fine then you should get the number of samples.

Hope this helps.

Best
