### ISSUE TITLE
Make test(s) failure 

### ISSUE THREAD

**Issue by grafau** [mfumagalli/ngsTools#16]
Hi there!

I would appreciate some help with installing ngsTools. After cloning latests version, running make and make tests, I get the following (on two completely different servers, CentOS 7.4.1708 and Ubuntu 16.04.3 LTS):

make[1]: Entering directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsSim'
ngsSim: test(s) failed!
make[1]: Leaving directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsSim'
make[1]: Entering directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsPopGen'
ngsPopGen: test(s) failed!
make[1]: Leaving directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsPopGen'
make[1]: Entering directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsUtils'
ngsUtils: test(s) failed!
make[1]: Leaving directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsUtils'
make[1]: Entering directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsDist'
ngsDist: test(s) failed!
make[1]: Leaving directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsDist'
make[1]: Entering directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsF'
ngsF: All tests OK!
make[1]: Leaving directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsF'
make[1]: Entering directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsF-HMM'
ngsF-HMM: test(s) failed!
make[1]: Leaving directory `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsF-HMM'

Any help would be much welcome!

Best,
Rafal

**Comment by mfumagalli** [comment]
Dear Rafal, yes it's a known issue but it shouldn't affect your installation. We'll fix it soon but in the while you can use ngsTools, it's just an issue with how we check that the installation works. I'll close it when done.

**Comment by grafau** [comment]
Dear Matteo,

Thank you for your reply! Perhaps those issues are unrelated then, but I cannot make ngsDist to work on both installations; I get the following error (any advice on how to proceed would be most welcome!):

*** Error in `/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsDist/ngsDist': free(): invalid pointer: 0x0000000001a2d1b4 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7fef5b296619]
/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsDist/ngsDist[0x4060ee]
/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsDist/ngsDist[0x40275e]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fef5b23bc05]
/storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsDist/ngsDist[0x402816]
======= Memory map: ========
00400000-0040e000 r-xp 00000000 08:11 90450039443                        /storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsDist/ngsDist
0060e000-0060f000 r--p 0000e000 08:11 90450039443                        /storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsDist/ngsDist
0060f000-00610000 rw-p 0000f000 08:11 90450039443                        /storage/rafal.gutaker/bin/INSTALLS/ngsTools/ngsDist/ngsDist
01a2a000-01eb1000 rw-p 00000000 00:00 0                                  [heap]
7fef54000000-7fef54021000 rw-p 00000000 00:00 0 
7fef54021000-7fef58000000 ---p 00000000 00:00 0 
7fef5a06f000-7fef5a0aa000 r-xp 00000000 fd:00 201450046                  /usr/lib64/libquadmath.so.0.0.0
7fef5a0aa000-7fef5a2a9000 ---p 0003b000 fd:00 201450046                  /usr/lib64/libquadmath.so.0.0.0
7fef5a2a9000-7fef5a2aa000 r--p 0003a000 fd:00 201450046                  /usr/lib64/libquadmath.so.0.0.0
7fef5a2aa000-7fef5a2ab000 rw-p 0003b000 fd:00 201450046                  /usr/lib64/libquadmath.so.0.0.0
7fef5a2ab000-7fef5a3ca000 r-xp 00000000 fd:00 201450037                  /usr/lib64/libgfortran.so.3.0.0
7fef5a3ca000-7fef5a5ca000 ---p 0011f000 fd:00 201450037                  /usr/lib64/libgfortran.so.3.0.0
7fef5a5ca000-7fef5a5cb000 r--p 0011f000 fd:00 201450037                  /usr/lib64/libgfortran.so.3.0.0
7fef5a5cb000-7fef5a5cd000 rw-p 00120000 fd:00 201450037                  /usr/lib64/libgfortran.so.3.0.0
7fef5a5cd000-7fef5b00c000 r-xp 00000000 fd:00 934138                     /usr/lib64/atlas/libsatlas.so.3.10
7fef5b00c000-7fef5b20c000 ---p 00a3f000 fd:00 934138                     /usr/lib64/atlas/libsatlas.so.3.10
7fef5b20c000-7fef5b211000 r--p 00a3f000 fd:00 934138                     /usr/lib64/atlas/libsatlas.so.3.10
7fef5b211000-7fef5b21a000 rw-p 00a44000 fd:00 934138                     /usr/lib64/atlas/libsatlas.so.3.10
7fef5b21a000-7fef5b3d2000 r-xp 00000000 fd:00 201328696                  /usr/lib64/libc-2.17.so
7fef5b3d2000-7fef5b5d2000 ---p 001b8000 fd:00 201328696                  /usr/lib64/libc-2.17.so
7fef5b5d2000-7fef5b5d6000 r--p 001b8000 fd:00 201328696                  /usr/lib64/libc-2.17.so
7fef5b5d6000-7fef5b5d8000 rw-p 001bc000 fd:00 201328696                  /usr/lib64/libc-2.17.so
7fef5b5d8000-7fef5b5dd000 rw-p 00000000 00:00 0 
7fef5b5dd000-7fef5b5f2000 r-xp 00000000 fd:00 202683014                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fef5b5f2000-7fef5b7f1000 ---p 00015000 fd:00 202683014                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fef5b7f1000-7fef5b7f2000 r--p 00014000 fd:00 202683014                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fef5b7f2000-7fef5b7f3000 rw-p 00015000 fd:00 202683014                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fef5b7f3000-7fef5b8f4000 r-xp 00000000 fd:00 203141107                  /usr/lib64/libm-2.17.so
7fef5b8f4000-7fef5baf3000 ---p 00101000 fd:00 203141107                  /usr/lib64/libm-2.17.so
7fef5baf3000-7fef5baf4000 r--p 00100000 fd:00 203141107                  /usr/lib64/libm-2.17.so
7fef5baf4000-7fef5baf5000 rw-p 00101000 fd:00 203141107                  /usr/lib64/libm-2.17.so
7fef5baf5000-7fef5bbde000 r-xp 00000000 fd:00 201328821                  /usr/lib64/libstdc++.so.6.0.19
7fef5bbde000-7fef5bdde000 ---p 000e9000 fd:00 201328821                  /usr/lib64/libstdc++.so.6.0.19
7fef5bdde000-7fef5bde6000 r--p 000e9000 fd:00 201328821                  /usr/lib64/libstdc++.so.6.0.19
7fef5bde6000-7fef5bde8000 rw-p 000f1000 fd:00 201328821                  /usr/lib64/libstdc++.so.6.0.19
7fef5bde8000-7fef5bdfd000 rw-p 00000000 00:00 0 
7fef5bdfd000-7fef5be14000 r-xp 00000000 fd:00 203228253                  /usr/lib64/libpthread-2.17.so
7fef5be14000-7fef5c013000 ---p 00017000 fd:00 203228253                  /usr/lib64/libpthread-2.17.so
7fef5c013000-7fef5c014000 r--p 00016000 fd:00 203228253                  /usr/lib64/libpthread-2.17.so
7fef5c014000-7fef5c015000 rw-p 00017000 fd:00 203228253                  /usr/lib64/libpthread-2.17.so
7fef5c015000-7fef5c019000 rw-p 00000000 00:00 0 
7fef5c019000-7fef5c02e000 r-xp 00000000 fd:00 201329064                  /usr/lib64/libz.so.1.2.7
7fef5c02e000-7fef5c22d000 ---p 00015000 fd:00 201329064                  /usr/lib64/libz.so.1.2.7
7fef5c22d000-7fef5c22e000 r--p 00014000 fd:00 201329064                  /usr/lib64/libz.so.1.2.7
7fef5c22e000-7fef5c22f000 rw-p 00015000 fd:00 201329064                  /usr/lib64/libz.so.1.2.7
7fef5c22f000-7fef5c26b000 r-xp 00000000 fd:00 204011104                  /usr/lib64/libgslcblas.so.0.0.0
7fef5c26b000-7fef5c46a000 ---p 0003c000 fd:00 204011104                  /usr/lib64/libgslcblas.so.0.0.0
7fef5c46a000-7fef5c46b000 r--p 0003b000 fd:00 204011104                  /usr/lib64/libgslcblas.so.0.0.0
7fef5c46b000-7fef5c46c000 rw-p 0003c000 fd:00 204011104                  /usr/lib64/libgslcblas.so.0.0.0
7fef5c46c000-7fef5c681000 r-xp 00000000 fd:00 204011102                  /usr/lib64/libgsl.so.0.16.0
7fef5c681000-7fef5c881000 ---p 00215000 fd:00 204011102                  /usr/lib64/libgsl.so.0.16.0
7fef5c881000-7fef5c884000 r--p 00215000 fd:00 204011102                  /usr/lib64/libgsl.so.0.16.0
7fef5c884000-7fef5c894000 rw-p 00218000 fd:00 204011102                  /usr/lib64/libgsl.so.0.16.0
7fef5c894000-7fef5c895000 rw-p 00000000 00:00 0 
7fef5c895000-7fef5c8b6000 r-xp 00000000 fd:00 201328671                  /usr/lib64/ld-2.17.so
7fef5ca95000-7fef5ca9e000 rw-p 00000000 00:00 0 
7fef5cab4000-7fef5cab6000 rw-p 00000000 00:00 0 
7fef5cab6000-7fef5cab7000 r--p 00021000 fd:00 201328671                  /usr/lib64/ld-2.17.so
7fef5cab7000-7fef5cab8000 rw-p 00022000 fd:00 201328671                  /usr/lib64/ld-2.17.so
7fef5cab8000-7fef5cab9000 rw-p 00000000 00:00 0 
7ffe92a27000-7ffe92a48000 rw-p 00000000 00:00 0                          [stack]
7ffe92aa4000-7ffe92aa6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

**Comment by fgvieira** [comment]
Hi Rafal,

Can you include the command you use and what ngsDist print to stdout?

thanks,

**Comment by grafau** [comment]
Sure, here it is:

ngsDist -verbose 1 -geno SA_Photo_noTrim.geno.gz -probs -n_ind 46 -n_sites 147158 -o SA_Photo_noTrim.dist -n_threads 12

**Comment by fgvieira** [comment]
Are you using the latest ngsDist version?
What angsd command did you use to get the geno file?
Can you share the input file? Maybe put it on dropbox...

thanks,

**Comment by grafau** [comment]
Hello Filipe,

Many thanks for your help, I have sent all the details directly to your snm.ku.dk e-mail. Please let me know if you have not received anything.

Best,
Rafal

**Comment by fgvieira** [comment]
Hi Rafal,

just ran it and it went fine (sent it to you by email).
Are you using the `angsd` that comes with `ngsTools`? If not, what version of `angsd` and `zlib` are you using?
I think the problem might be that `ngsDist` in `ngsTools` is not the latest version (get the latest [here](https://github.com/fgvieira/ngsDist)); the reason why is that `angsd` is under heavy development and keeps changing (e.g. options, format, etc...), and so every time it changes we need to make sure everything is still compatible with `ngsTools`.

**Comment by grafau** [comment]
Hi Filipe,

Great, thanks for your help both to you and Matteo. I didn't realize that ngsDist github has newer version than ngsTools github (and also that I should probably have reported my issue there). 

Just in case anyone else runs into similar problems:
I am running:
ANGSD 0.921
zlib 1.2.8
ngsDist 1.0.2 (is included in ngsTools clone and doesn't work with my GL files)
ngsDist 1.0.4 (is included in ngsDist clone and works well with me)

Thank you for your support!
Best,
Rafal

**Comment by fgvieira** [comment]
Yes, sometimes it is a bit tricky to keep up with all the changes in `ANGSD`.
Sorry about that and I'll try to update `ngsTools` soon.

best,
