### ISSUE TITLE
error while running plotPCA.R

### ISSUE THREAD

**Issue by manonpr** [mfumagalli/ngsTools#21]
Dear Dr Fumagalli,

I'm trying to use your plotPCA.R script through:
`Rscript --vanilla --slave pca.R -i ${in}.covMat -c 1-2 -a ${bamclst}.clst -o ${out}.pdf`

with a .covMat file I generated from the following angsd command:
  ```
angsd -bam ${bamlist} -out ${out} -nThreads 8 \
        -minMapQ 20 -minQ 20 -minInd ${minInd} -doCounts 1 \
        -GL 1 -doMajorMinor 1 -doMaf 1 -minMaf 0.05 -skipTriallelic 1 \
        -SNP_pval 1e-6 -doHWE 1 -minHWEpval 0.05 -doPost 2 -postCutoff 0.95 \
        -doGeno 4 -geno_minDepth 5 -doGlf 2 -doIBS 1 -doCov 1
```

But I get the following error message :
> Error in eigen(covar, symm = TRUE) : infinite or missing values in 'x'
> Execution halted

I don't understand the issue because I don't have any missing data in my .covMat file.
Do you know what this message means?

Best regards,
Manon

**Comment by mfumagalli** [comment]
Dear Manon,

plotPCA.R was written for the output of ngsCovar in ngsTools. I have never tried it from the output of ANGSD so I am not sure it's compatible.

Matteo
________________________________
