### ISSUE TITLE
COMPILATION ERROR

### ISSUE THREAD

**Issue by jotes35** [mfumagalli/ngsTools#22]
Hi , I tried installing ngsTools and I got this error. Please advice

No package 'gsl' found
make[1]: Entering directory `/home/ha/apps/bioinfo/ngsTools/ngsTools/ngsDist'
g++ -I./shared  -O3 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -c ./shared/gen_func.cpp
In file included from ./shared/gen_func.cpp:1:0:
./shared/gen_func.hpp:12:25: fatal error: gsl/gsl_rng.h: No such file or directory
 #include <gsl/gsl_rng.h>

But I have gsl installed ( in a non-default linux directory)

**Comment by mfumagalli** [comment]
If you have issues with gsl package, then on linux make sure you have these packages installed: gsl-bin libgsl-dbg libgsl-dev libgs1l23 libgslcblas0.

**Comment by jotes35** [comment]
Thanks. It is working now.
