### ISSUE TITLE
TESTS FAILED

### ISSUE THREAD

**Issue by jotes35** [mfumagalli/ngsTools#23]
Hi. I installed the ngsTools on my ubuntu machine using the make command. I run the make test and some of the tests failed. Is there anything to be concerned about ?  Below is the log

_make[1]: Entering directory '/home/user/ngsTools/ngsSim'
ngsSim: All tests OK!
make[1]: Leaving directory '/home/user/ngsTools/ngsSim'
make[1]: Entering directory '/home/user/ngsTools/ngsPopGen'
ngsPopGen: All tests OK!
make[1]: Leaving directory '/home/user/ngsTools/ngsPopGen'
make[1]: Entering directory '/home/user/ngsTools/ngsUtils'
ngsUtils: All tests OK!
make[1]: Leaving directory '/home/user/ngsTools/ngsUtils'
make[1]: Entering directory '/home/user/ngsTools/ngsDist'
ngsDist: All tests OK!
make[1]: Leaving directory '/home/user/ngsTools/ngsDist'
make[1]: Entering directory '/home/user/ngsTools/ngsLD'
ngsLD: test(s) failed!
make[1]: Leaving directory '/home/user/ngsTools/ngsLD'
make[1]: Entering directory '/home/user/ngsTools/ngsF'
ngsF: All tests OK!
make[1]: Leaving directory '/home/user/ngsTools/ngsF'
make[1]: Entering directory '/home/user/ngsTools/ngsF-HMM'
ngsF-HMM: test(s) failed!
make[1]: Leaving directory '/home/user/ngsTools/ngsF-HMM'_

**Comment by mfumagalli** [comment]
please look into individal repos of ngsLD and ngsF-HMM for extra requirements and packages needed
