### ISSUE TITLE
Tutorial command not running

### ISSUE THREAD

**Issue by vappiah** [mfumagalli/ngsTools#26]
Hello @mfumagalli . I tried following the tutorial given for ngsTools and it could not run. Below is the command I used

$ANGSD -P 36 -b ALL.bamlist -ref $REF -out Results/ALL.qc -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 1 -minMapQ 20 -minQ 20 -minInd 15 -setMinDepth 60 -setMaxDepth 400 -doCounts 1 -GL 1 -doMajorMinor 1 -doMaf 1 -skipTriallelic 1 -SNP_pval 1e-3 -doGeno 32 -doPost 1 &> /dev/null

Below is the message that was displayed
	_-> angsd version: 0.930 (htslib: 1.9) build(Jan  3 2021 13:10:41)
	-> angsd version: 0.930 (htslib: 1.9) build(Jan  3 2021 13:10:41)
	-> Please use the website "http://www.popgen.dk/angsd" as reference
	-> Use -nThreads or -P for number of threads allocated to the program
Overview of methods:_Below is the message that was displayed
	-GL		Estimate genotype likelihoods
	-doCounts	Calculate various counts statistics
	-doAsso		Perform association study
	-doMaf		Estimate allele frequencies
	-doError	Estimate the type specific error rates
	-doAncError	Estimate the errorrate based on perfect fastas
	-HWE_pval	Est inbreedning per site or use as filter
	-doGeno		Call genotypes
	-doFasta	Generate a fasta for a BAM file
	-doAbbababa	Perform an ABBA-BABA test
	-sites		Analyse specific sites (can force major/minor)
	-doSaf		Estimate the SFS and/or neutrality tests genotype calling
	-doHetPlas	Estimate hetplasmy by calculating a pooled haploid frequency

	Below are options that can be usefull
	-bam		Options relating to bam reading
	-doMajorMinor	Infer the major/minor using different approaches
	-ref/-anc	Read reference or ancestral genome
	-doSNPstat	Calculate various SNPstat
	-cigstat	Printout CIGAR stat across readlength
	many others

Output files:
	 In general the specific analysis outputs specific files, but we support basic bcf output
	-doBcf		Wrapper around -dopost -domajorminor -dofreq -gl -dovcf docounts
For information of specific options type: 
	./angsd METHODNAME eg 
		./angsd -GL
		./angsd -doMaf
		./angsd -doAsso etc
		./angsd sites for information about indexing -sites files
Examples:
	Estimate MAF for bam files in 'list'
		'./angsd -bam list -GL 2 -doMaf 2 -out RES -doMajorMinor 1'__

**Comment by fgvieira** [comment]
Did you initialize the variables `$ANGSD` and `$REF`?
What is the content of file `ALL.bamlist`?

**Comment by vappiah** [comment]
Yes I did. This is ALL.bamlist content
Data/LWK.BAMs/NA19017.mapped.ILLUMINA.bwa.LWK.low_coverage.20121211.bam.sort.bam
Data/LWK.BAMs/NA19019.mapped.ILLUMINA.bwa.LWK.low_coverage.20121211.bam.sort.bam
Data/LWK.BAMs/NA19020.mapped.ILLUMINA.bwa.LWK.low_coverage.20130415.bam.sort.bam
Data/LWK.BAMs/NA19023.mapped.ILLUMINA.bwa.LWK.low_coverage.20121211.bam.sort.bam
Data/LWK.BAMs/NA19024.mapped.ILLUMINA.bwa.LWK.low_coverage.20121211.bam.sort.bam
Data/LWK.BAMs/NA19025.mapped.ILLUMINA.bwa.LWK.low_coverage.20130415.bam.sort.bam
Data/LWK.BAMs/NA19313.mapped.ILLUMINA.bwa.LWK.low_coverage.20120522.bam.sort.bam
Data/LWK.BAMs/NA19331.mapped.ILLUMINA.bwa.LWK.low_coverage.20120522.bam.sort.bam
Data/LWK.BAMs/NA19434.mapped.ILLUMINA.bwa.LWK.low_coverage.20120522.bam.sort.bam
Data/LWK.BAMs/NA19445.mapped.ILLUMINA.bwa.LWK.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01565.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01566.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01571.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01572.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01577.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01578.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01892.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01893.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01917.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/PEL.BAMs/HG01918.mapped.ILLUMINA.bwa.PEL.low_coverage.20120522.bam.sort.bam
Data/TSI.BAMs/NA20502.mapped.ILLUMINA.bwa.TSI.low_coverage.20120522.bam.sort.bam
Data/TSI.BAMs/NA20503.mapped.ILLUMINA.bwa.TSI.low_coverage.20130415.bam.sort.bam
Data/TSI.BAMs/NA20504.mapped.ILLUMINA.bwa.TSI.low_coverage.20130415.bam.sort.bam
Data/TSI.BAMs/NA20505.mapped.ILLUMINA.bwa.TSI.low_coverage.20130415.bam.sort.bam
Data/TSI.BAMs/NA20506.mapped.ILLUMINA.bwa.TSI.low_coverage.20130415.bam.sort.bam
Data/TSI.BAMs/NA20507.mapped.ILLUMINA.bwa.TSI.low_coverage.20130415.bam.sort.bam
Data/TSI.BAMs/NA20508.mapped.ILLUMINA.bwa.TSI.low_coverage.20130415.bam.sort.bam
Data/TSI.BAMs/NA20509.mapped.ILLUMINA.bwa.TSI.low_coverage.20130415.bam.sort.bam
Data/TSI.BAMs/NA20510.mapped.ILLUMINA.bwa.TSI.low_coverage.20130415.bam.sort.bam
Data/TSI.BAMs/NA20511.mapped.ILLUMINA.bwa.TSI.low_coverage.20130415.bam.sort.bam

**Comment by vappiah** [comment]
Interestingly when I issue this command nothing happens
$ANGSD/angsd -P 4 -b ALL.bamlist -ref $REF -out Results/ALL.qc -r 11\
        -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 1 \
	-minMapQ 20 \
        -doQsDist 1 -doDepth 1 -doCounts 1 -maxDepth 500 &> /dev/null

But when I issue like this it begins run 
$ANGSD -P 8 -b ALL.bamlist -ref $REF -out Results/ALL.qc -r 11

**Comment by vappiah** [comment]
This is the entire script 

NGSTOOLS=/opt/apps/ngsTools/ngsTools

ANGSD=$NGSTOOLS/angsd/angsd
NGSADMIX=/opt/apps/NGSadmix/32/NGSadmix

SAMTOOLS=/opt/apps/samtools/1.10/bin/samtools
HTSLIB=$NGSTOOLS/htslib
FASTME=/opt/apps/FastME/2.1.6/fastme

REF=Data/ref.fa.gz
ANC=Data/anc.fa.gz

#$ANGSD
$ANGSD/angsd -P 4 -b ALL.bamlist -ref $REF -out Results/ALL.qc -r 11\
        -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 1 \
        -minMapQ 20 \
        -doQsDist 1 -doDepth 1 -doCounts 1 -maxDepth 500 &> /dev/null

**Comment by fgvieira** [comment]
To make the QC plots, you need to also use options `-doQsDist 1 -doDepth 1` and set `-maxDepth` to some reasonable value.
