### ISSUE TITLE
How to use plotSFS.R for SFS plot?

### ISSUE THREAD

**Issue by sunshichao0916** [mfumagalli/ngsTools#28]
Dear mfumagalli,
     
Now, I have three population SFS files,  and want to use plotSFS.R to plot a figure of SFS. However, I dont't know how to do.
I tried to use command `R CMD BATCH plotSFS.R pop1.sfs pop2.sfs pop3.sfs` , but with false output file named NA. 

The formate of input file :
`1501016844.282213 305197949.866378 94107367.693417 28784361.230037 12232819.391580 8848907.018584 4452457.953427 6221102.970627 2647028.357635 3060544.718254`

Hope your answer.
Thank you very much!

Sun

**Comment by mfumagalli** [comment]
please look at the tutorial or example here https://github.com/nt246/physalia-lcwgs/blob/main/day_4/markdowns/01_sfs.md to plot the SFS; anyway, it's simply a barplot so any script reading the output file and producing a barplot would work.
