### ISSUE TITLE
cannot estimate fst due problem with size of dimension of 2d SFS

### ISSUE THREAD

**Issue by marce-sarrias** [mfumagalli/ngsTools#29]
Hi there, 

I've been following this tutorial (which is great btw!) without any problem until now :( 
For some reason I am not able to estimate fst. 

I have what I believe are 2 different populations (the whole point of doing these analyses is to actually see if they are different or not): pop1 (n = 10) and pop2 (n =10)

So far, this is what I've done:

1 -> calculate SAF: 
 (I'm using my reference genome as the ancestral sequence to polarise the alleles)
FILTERS="-minMapQ 30 -minQ 20 -uniqueOnly 1 -remove_bads 1 -baq 1 -only_proper_pairs 1 -trim 0 -C 50 -maxDepth 500 -minInd 10 -setMinDepth 20 -setMaxDepth 100"
$ANGSD -b pop1.bam.list -anc $ANC -ref $REF $FILTERS -GL 1 -doCounts 1 -doSaf 1 -out pop1
$ANGSD -b pop2.bam.list -anc $ANC -ref $REF $FILTERS -GL 1 -doCounts 1 -doSaf 1 -out pop2

2 -> calculate SFS:
$realSFS -bootstrap 100 pop1.saf.idx > pop1.sfs
$realSFS -bootstrap 100 pop2.saf.idx > pop2.sfs

Then I checked the number of values by doing:
awk -F' ' '{print NF; exit}' pop1.sfs  
awk -F' ' '{print NF; exit}' pop2.sfs  
awk -F' ' '{print NF; exit}' pop1.pop2.sfs  

and I get 21 (2N+1), 21, and 441 respectively

3 -> calculate 2d SFS:
$realSFS -bootstrap 100 pop1.saf.idx pop2.saf.idx > pop1.pop2.sfs

now I'm trying to calculate the fst by doing:
$realSFS fst index pop1.saf.idx pop2.saf.idx -sfs pop1.pop2.sfs -fstout pop1.pop2
$realSFS fst stats pop1.po2.fst.idx
 
but I get this error: 
	-> args: tole:0.000000 nthreads:4 maxiter:100 nsites(block):0 start:pop1.pop2.sfs chr:(null) start:-1 stop:-1 fstout:pop1.pop2 oldout:0 seed:-1 bootstrap:0 resample_chr:0 whichFst:0 fold:0 ref:(null) anc:(null)
	-> nSites: 100000
	-> IMPORTANT: please make sure that your saf files haven't been folded with -fold 1 in -doSaf in angsd
	-> [reynoldFst] sfs1:20 sfs2:20 dimspace:441 
	-> generating offset remapper lookup
	-> isSame:1 adjusting foldfactors
	-> Reading: pop1.pop2.sfs assuming counts (will normalize to probs internally)
	-> Pxroblem with size of dimension of prior 441 vs 44100

I can't figure out what I've done wrong... Any ideas?

Thank you!

Marcela

**Comment by mfumagalli** [comment]
Hi Marcela, can you please let us know which version of angsd are you using? Or, if from github, the commit number? Thanks.
________________________________
From: marce-sarrias ***@***.***>
Sent: 10 July 2022 7:06 AM
To: mfumagalli/ngsTools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mfumagalli/ngsTools] cannot estimate fst due problem with size of dimension of 2d SFS (Issue #29)


Hi there,

I've been following this tutorial (which is great btw!) without any problem until now :(
For some reason I am not able to estimate fst.

I have what I believe are 2 different populations (the whole point of doing these analyses is to actually see if they are different or not): pop1 (n = 10) and pop2 (n =10)

So far, this is what I've done:

1 -> calculate SAF:
(I'm using my reference genome as the ancestral sequence to polarise the alleles)
FILTERS="-minMapQ 30 -minQ 20 -uniqueOnly 1 -remove_bads 1 -baq 1 -only_proper_pairs 1 -trim 0 -C 50 -maxDepth 500 -minInd 10 -setMinDepth 20 -setMaxDepth 100"
$ANGSD -b pop1.bam.list -anc $ANC -ref $REF $FILTERS -GL 1 -doCounts 1 -doSaf 1 -out pop1
$ANGSD -b pop2.bam.list -anc $ANC -ref $REF $FILTERS -GL 1 -doCounts 1 -doSaf 1 -out pop2

2 -> calculate SFS:
$realSFS -bootstrap 100 pop1.saf.idx > pop1.sfs
$realSFS -bootstrap 100 pop2.saf.idx > pop2.sfs

Then I checked the number of values by doing:
awk -F' ' '{print NF; exit}' pop1.sfs
awk -F' ' '{print NF; exit}' pop2.sfs
awk -F' ' '{print NF; exit}' pop1.pop2.sfs

and I get 21 (2N+1), 21, and 441 respectively

3 -> calculate 2d SFS:
$realSFS -bootstrap 100 pop1.saf.idx pop2.saf.idx > pop1.pop2.sfs

now I'm trying to calculate the fst by doing:
$realSFS fst index pop1.saf.idx pop2.saf.idx -sfs pop1.pop2.sfs -fstout pop1.pop2
$realSFS fst stats pop1.po2.fst.idx

but I get this error:
-> args: tole:0.000000 nthreads:4 maxiter:100 nsites(block):0 start:pop1.pop2.sfs chr:(null) start:-1 stop:-1 fstout:pop1.pop2 oldout:0 seed:-1 bootstrap:0 resample_chr:0 whichFst:0 fold:0 ref:(null) anc:(null)
-> nSites: 100000
-> IMPORTANT: please make sure that your saf files haven't been folded with -fold 1 in -doSaf in angsd
-> [reynoldFst] sfs1:20 sfs2:20 dimspace:441
-> generating offset remapper lookup
-> isSame:1 adjusting foldfactors
-> Reading: pop1.pop2.sfs assuming counts (will normalize to probs internally)
-> Pxroblem with size of dimension of prior 441 vs 44100

I can't figure out what I've done wrong... Any ideas?

Thank you!

Marcela

**Comment by mfumagalli** [comment]
good, I will close the issue then.
