### ISSUE TITLE
visualization 2DSFS. plot2DSFS.R

### ISSUE THREAD

**Issue by yangwukaidi** [mfumagalli/ngsTools#31]
hi
Thank you very much for your valuable sharing.
Recently, I had a problem using plot2DSFS.R.
The command I used was as follows,
Rscript plot2DSFS.R HNHZ.YZ.sfs HNHZ-YZ 27-28
But instead of a raster, I got a strange one, as follows
![1680575567157](https://user-images.githubusercontent.com/127917612/229744590-568b32f5-25dd-4e39-b180-8f4b9ed08045.png)
Can you tell me what causes this?
I am looking forward to your reply!

**Comment by mfumagalli** [comment]
hi, did you use ANGSD and realSFS to estimate the 2D-SFS? did you obtain a matrix as final estimation or a flatten vector (if you open the text file)? it may be due to changes in how ANGSD returns the output of the estimated SFS.

**Comment by mfumagalli** [comment]
that means that the old plot2dsfs.r script is not compatible with the latest version of ANGSD. I recommend to check if ANGSD provides their own scripts for plotting.
