### ISSUE TITLE
how to prepare sfs input file?

### ISSUE THREAD

**Issue by lvfenghua** [mfumagalli/ngsTools#7]
I used below code to run, it printed a error "Possible error,binaryfiles might be broken"
/home/lvfh/Tools-Reseq/ngsTools/ngsPopGen/ngsCovar -probfile test.pops.geno -outfile test.covar -nind 10 -nsites 10000 -block_size 2000 -call 0 -sfsfile test.sfs.ml.norm
So, i used an another code "/home/lvfh/Tools-Reseq/ngsTools/ngsPopGen/ngsCovar -probfile test.pops.geno -outfile test.covar -nind 10 -nsites 10000 -block_size 2000 -call 0". i got a right results. 
I used  the following commands to output .sfs files :
"angsd -b bam.filelist -anc chimpHg19.fa -out test -P 5 -r 1: -GL 1 -doSaf 1" "realSFS test.saf.idx -maxIter 100 -P 5 > test.sfs" .

**Comment by fgvieira** [comment]
Dear,

sorry for the late reply, but we've been updating ngsTools.
Did you manage to solve your issue? If not, I'd recommend taking a look at ngsTools tutorial file. If you still can not solve it, could you elaborate a bit more on what you are trying to do?

best,
FGV
