### ISSUE TITLE
angsd repo link is broken

### ISSUE THREAD

**Issue by lecorguille** [mfumagalli/ngsTools#8]
Hi,

The link to angsd is broken.

I used this repo : https://github.com/ANGSD/angsd

And processed as mentionned in the README.

git clone https://github.com/samtools/htslib.git;
git clone https://github.com/angsd/angsd.git;
cd htsdir;make;cd ../angsd;make HTSSRC=../htslib

It's seem good

**Comment by lecorguille** [comment]
I didn't see that "only with versions of ANGSD <0.800"

So, I tried to compile the 0.700 but I got a problem about version.h
Although, I didn't know if it's a < or a <=, I install the 0.800.

I'm not the user-end, I will let him try my combinaison.
Meanwhile, if you have the truth, I'm interested.

Thanks

**Comment by zhensydow** [comment]
I also founded a broken link with error:

    git submodule update
    fatal: reference is not a tree: 869f5194d6a06e36e5511034ba726e99c5d75792
    Unable to checkout '869f5194d6a06e36e5511034ba726e99c5d75792' in submodule path 'angsd'

**Comment by jpuritz** [comment]
I can confirm this problem as well.

**Comment by fgvieira** [comment]
Dear all,

currently, ngsTools only supports ANGSD < v0.8 and, since ANGSD author changed some commits, the link is not working. We are currently working to fix and update everything to the latest ANGSD version and, hopefully, it will be done in 1 or 2 weeks.

Sorry for the inconvenience.
FGV

**Comment by fgvieira** [comment]
We have just updated ngsTools to work with latest ANGSD version.

best,
FGV
