### ISSUE TITLE
segfault with some -offset / -nsites combinations

### ISSUE THREAD

**Issue by marqueda** [mfumagalli/ngsTools#9]
Dear Matteo,

I am getting a segmentation fault when running ngsCovar for data subsets using **-offset** and **-nsites** options - I suspect this could be a bug.

I am running the following command with the latest github version of ngsCovar and get the following verbose output (args and dumping file lines removed):
>$ ngsCovar -probfile file.geno -nind 58 -verbose 1 -offset 400000 -nsites 193 -norm 0 -call 0 -sfsfile file.saf -outfile tmp1
>Block 0 out of 0 from 399999 to 400191
>Getting esti...: 193 174 , 0.969347 0.059351
>Getting mu...: 193, 0.286054 0.115822
>Updating covar......weighting...
>Got  sfs: 193 117, e.g. 0.000000 0.000000
>Getting pvar...: 193 , 1.000000 1.000000
>Updating covar...Segmentation fault

I get the same when not using -sfsfile:
>$ ngsCovar -probfile file.geno -nind 58 -verbose 1 -offset 148028 -nsites 327 -norm 0 -call 0 -outfile tmp1
>Block 0 out of 0 from 148027 to 148353
>Getting esti...: 327 174 , 0.984398 0.015602
>Getting mu...: 327, 0.071430 0.074497
>Updating covar...
> I am using this minmaf 0.000000 ...no weighting...Segmentation fault

While for some other combinations of -offset and -nsites, it works:
>$ ngsCovar -probfile file.geno -nind 58 -verbose 1 -offset 148027 -nsites 329 -norm 0 -call 0 -sfsfile file.saf -outfile tmp1**
>Block 0 out of 0 from 148026 to 148354
>Getting esti...: 329 174 , 0.000000 0.015602
>Getting mu...: 329, 0.169526 0.048822
>Updating covar......weighting...
>Got  sfs: 329 117, e.g. 0.000000 0.186886
>Getting pvar...: 329 , 1.000000 0.999999
>Updating covar...
>Updating esite...: 309.205395    Sum:4383384258618.480957
>(Exp/eff) nr sites: 309.205395

I use geno/saf files created with angsd 0.911 (newest github version) from a BEAGLE input file containing around 7M SNPs, so the geno and saf files (both binary) should contain information on 7M sites. I observed that the subsetting worked fine for low numbers supplied to **-offset**, but that with high numbers (= high index of starting site), the segfault happens. To test this, I ran the same data subset once using the full 7M SNP geno/saf files (-> segfault) and once using geno/saf files only containing the data subset of interest (-> worked nicely). The index number (1 vs. 27000000) supplied to **-offset** was thus the only difference.

Thank you very much for any ideas or input on what I could be wrong or whether this could be a bug.
Best,
David

**Comment by fgvieira** [comment]
Hi David,

thanks for the (quite extensive) bug report!
From what you say, and since it seems to work with smaller values of offset, it might be related to the fact that ngsCovar uses an `int` to store the offset, but it is a bit hard to be sure just from your description. I know the input file might be a bit big, but do you think you can send both the geno and SFS files (together with some commands that failed and some others that worked)?

thanks,
FGV

PS - maybe use Dropbox or something similar...
